### ISSUE TITLE
Support React 18?

### ISSUE THREAD

**Issue by neillindberg** [silversonicaxel/storybook-addon-versioning#2]
I really dig this plugin, but I'm finding with React > 17 I need to use `--force` when installing. I don't see any reason that this couldn't be bumped to work with React 18. Would this be a problem todo?
`"react": "^16.8.0 || ^17.0.0 || ^18.0.0",`

Thank you,
Neil

**Comment by silversonicaxel** [comment]
Hello @neillindberg , I would love to help sure. 
I can propose a PR to set peerDependencies in this file https://github.com/silversonicaxel/storybook-addon-versioning/blob/main/package.json as you are requesting. I don't see indeed a big issue doing this.

**Comment by silversonicaxel** [comment]
@neillindberg does this PR https://github.com/silversonicaxel/storybook-addon-versioning/pull/3 solve the issue? 
we have a new version 0.1.1 https://www.npmjs.com/package/storybook-version

**Comment by neillindberg** [comment]
That did it! Thank you so much :)
