### ISSUE TITLE
Upgrade to Storybook 7.X

### ISSUE THREAD

**Issue by nextrie** [silversonicaxel/storybook-addon-versioning#4]
Hello ! First of all, thank you for publishing this package.
I was wondering if you could upgrade the Storybook version to version 7.X ?

Upgrading would help us stay up-to-date and improve our development workflow

Thank you and have a great day

**Comment by silversonicaxel** [comment]
@nextrie feel free to open a PR, otherwise I will try to work on this as soon as I will have some time.

**Comment by silversonicaxel** [comment]
Done https://github.com/silversonicaxel/storybook-addon-versioning/pull/6
